# Generated by Django 5.0.6 on 2024-07-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='es_administrador',
            field=models.BooleanField(default=False),
        ),
    ]
